import streamlit as st
import datetime
import requests
from config.save_to_documnet import save_document

url = "http://localhost:8000/query"

st.set_page_config(layout="centered",
                   initial_sidebar_state="expanded",
                   page_title="Trip Planner")

st.title("AI Trip Planner")

if "messages" not in st.session_state:
    st.session_state.messages = []


with st.form(key="query_form",clear_on_submit=True):
    st.subheader("🗺️ Hello! I’m your AI Travel Agent — how can I make your journey amazing today?")
    user_input = st.text_input("enter query")
    submit = st.form_submit_button("submit")



if submit and user_input.strip():
    try:
        with st.spinner("Generating"):
            payload = {"question":user_input}
            response = requests.post(url,json=payload)

            if response.status_code==200:
                answer = response.json().get("answer","no answer returned")
                markdown_content = f"""

                Haseeb Travel Agency,

                {answer}

                This plan is generated by AI please verify it as it can make mistake
                """

                st.markdown(markdown_content)
            else:
                st.error("Error connecting to the API "+response.text)

            filename = save_document(answer)
            if filename:
                st.success(f"✅ Your trip plan has been saved to: `{filename}`")
            else:
                st.warning("⚠️ Failed to save your trip plan.")

    except Exception as e:
        st.error(f"An error occure while connecting to API: {e}")
    



