FROM python:3.12-slim


# Environment variable: Don't write .pyc files(__pycache__)
ENV PYTHONDONTWRITEBYTECODE=1

# Environment variable: Enable output buffering (set to 1 for stdout to show immediately)
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --upgrade pip &&\
    pip install uv && \
    uv pip install --system -r requirements.txt

COPY backend/ .         
COPY src/ ./src/
        

EXPOSE 8000

CMD ["uvicorn","app:app","--host","0.0.0.0","--port","8000"]