import os,datetime

def save_document(response_text:str ,directory:str="./output"):

    os.makedirs(directory,exist_ok=True)
    markdown_content = f"""# Ai travel Agent
    ---
    
    {response_text}


    ---
    This plan is generated by AI please verify it as it can make mistakes.
    
    """
    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/Trip organizer AI agent llmops{timestamp}.md"

        with open(filename,"w",encoding="utf-8") as f:
            f.write(markdown_content)
        print(f"MArkdown file saved as  -->  {filename}")

        return filename
    except Exception as e:
        print(f"Error saving markdown file,{e}")
        return None
    

